namespace: eshop
protcol: http
apiGatewayUrlExternal: webshopping-gw.eshop.boringtestdomain.nl
identityUrlExternal: identity-api.eshop.boringtestdomain.nl
blazorClientUrlExternal: blazor-client.eshop.boringtestdomain.nl
seqFqdn: seq.eshop.boringtestdomain.nl