kind: ConfigMap
apiVersion: v1
metadata:
  name: identity-cm
  namespace: {{ .Values.global.namespace }}
  labels:
    app: eshop
    service: identity
data:
  ASPNETCORE_ENVIRONMENT: Development
  ASPNETCORE_URLS: http://0.0.0.0:80
  SeqServerUrl: http://{{ .Values.global.seqFqdn }}
  IdentityUrl: {{ .Values.global.protocol }}://{{ .Values.global.identityUrlExternal }}
  IdentityUrlExternal: {{ .Values.global.protocol }}://{{ .Values.global.identityUrlExternal }}
  BlazorClientUrlExternal: {{ .Values.global.protocol }}://{{ .Values.global.blazorClientUrlExternal }}
  IssuerUrl: {{ .Values.global.protocol }}://{{ .Values.global.identityUrlExternal }}
  #BasketApiUrlExternal: http://{{ .Values.externalDnsNameOrIP}}:30005
  #OrderingApiUrlExternal: http://{{ .Values.externalDnsNameOrIP}}:30002
  #ShoppingAggregatorApiUrlExternal: http://{{ .Values.externalDnsNameOrIP}}:30006
  # Temporarily while waiting for https://github.com/dapr/dotnet-sdk/issues/779 to get fixed.
  #ConnectionStrings__IdentityDB: Server=sqldata;Database=Microsoft.eShopOnDapr.Service.IdentityDb;User Id=sa;Password=Pass@word;TrustServerCertificate=true
  ConnectionStrings__IdentityDB: {{ .Values.global.sqlConnectionString }}


---

kind: Deployment
apiVersion: apps/v1
metadata:
  name: identity
  namespace: {{ .Values.global.namespace }}
  labels:
    app: eshop
    service: identity
spec:
  replicas: 1
  selector:
    matchLabels:
      service: identity
  template:
    metadata:
      labels:
        app: eshop
        service: identity
      annotations:
        dapr.io/enabled: "true"
        dapr.io/app-id: "identity-api"
        dapr.io/app-port: "80"
        dapr.io/config: "dapr-config"
        dapr.io/log-as-json: "true"
    spec:
      containers:
        - name: identity-api
          image: demo01cr.azurecr.io/identity.api:{{ .Values.identityImageTag }}
          imagePullPolicy: IfNotPresent
          ports:
            - name: http
              containerPort: 80
              protocol: TCP
          envFrom:
            - configMapRef:
                name: identity-cm
          readinessProbe:
            httpGet:
              path: /hc
              port: 80
            initialDelaySeconds: 5
            periodSeconds: 5

---

kind: Service
apiVersion: v1
metadata:
  name: identity-api
  namespace: {{ .Values.global.namespace }}
  labels:
    app: eshop
    service: identity
spec:
  ports:
    - port: 80
      targetPort: 80
      protocol: TCP
      name: http
  selector:
    service: identity