# global variable for application
global:
  namespace: eshop
  protocol: https
  hostName: webshop.internal.io
  containerRegistry: demo01cr.azurecr.io #eshopdapr #or demo01cr.azurecr.io

secrets:
  keyVaultName: my-keyvault-name
  # aksSecretProviderEnabled is for Secrets Store CSI Driver in an AKS cluster
  aksSecretProviderEnabled: false
  # tenantId for is for Secrets Store CSI Driver to authenticate to the KeyVault
  tenantId: 00000000-0000-0000-0000-000000000000
  # keyVaultClientId is needed if Dapr uses the KeyVault
  keyVaultClientId: 00000000-0000-0000-0000-000000000000

ingress:
  forceSSLRedirect: false
  certManager:
    # enabled can be set to true if cert-manager is installed and used
    enabled: false
    #environment can be staging or prod
    environment: staging
  tls: []
#    - secretName: webshop-internal-io-tls
#      hosts:
#        - webshop.internal.io

dapr:
  pubsub:
    azureEnabled: false

# tags
apiGatewayTag: latest
basketImageTag: latest
blazorClientImageTag: latest
catalogImageTag: latest
identityImageTag: latest
orderingImageTag: latest
paymentImageTag: latest
webshoppingaggImageTag: latest

identity:
  sqlConnectionStringDev: |
    - name: ConnectionStrings__IdentityDB
      value: Server=sqldata;Database=Microsoft.eShopOnDapr.Service.IdentityDb;User Id=sa;Password=Pass@word;TrustServerCertificate=true
  secretProviderVolume: []
  #secretProviderVolume: |
  #  volumes:
  #    - name: secrets-store01-inline
  #      csi:
  #        driver: secrets-store.csi.k8s.io
  #        readOnly: true
  #        volumeAttributes:
  #          secretProviderClass: "azure-csi-secret-provider"
  secretProviderVolumeMount: []
  #secretProviderVolumeMount: |
  #  volumeMounts:
  #    - name: secrets-store01-inline
  #      mountPath: "/mnt/secrets-store"
  sqlConnectionStringProd: []
  #sqlConnectionStringEnvironmentVariable: |
  #  - name: ConnectionStrings__IdentityDB
  #    valueFrom:
  #      secretKeyRef:
  #        name: sql-connection-string-secret
  #        key: secret
