apiVersion: dapr.io/v1alpha1
kind: Component
metadata:
  name: servicebus-pubsub
  namespace: eshop
spec:
  type: pubsub.azure.servicebus
  version: v1
  metadata:
    - name: connectionString # Required when not using Azure Authentication.
      value: "Endpoint=sb://kube-sbx-a-sb-ns.servicebus.windows.net/;SharedAccessKeyName=RootManageSharedAccessKey;SharedAccessKey=<**>"
