apiVersion: dapr.io/v1alpha1
kind: Component
metadata:
  name: azurekeyvault
  namespace: {{ .Values.namespace }}
spec:
  type: secretstores.azure.keyvault
  version: v1
  metadata:
    - name: vaultName
      value: {{ .Values.keyVaultName }}
    - name: spnClientId
      value: {{ .Values.dapr.keyVaultClientId }}