{
 "title": "knowledge session custom dashboard",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "pod per ns",
   "type": "barchart",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "sum by (namespace) (kube_pod_info)",
     "legendFormat": "{{namespace}}"
    }
   ]
  },
  {
   "title": "restarting pods",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "sum by (namespace)(changes(kube_pod_status_ready{condition=\"true\"}[5m]))",
     "legendFormat": "{{namespace}}"
    }
   ]
  },
  {
   "title": "container memory",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "topk(10,sum(container_memory_working_set_bytes{namespace=\"eshop\"}) by (container))",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "cpu usage",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "\nsum(rate(container_cpu_user_seconds_total{namespace=\"eshop\"}[120s])) by (container)",
     "legendFormat": "{{pod}}"
    }
   ]
  }
 ]
}