ingress:
  enabled: true
  annotations:
    kubernetes.io/ingress.class: "nginx"
    nginx.ingress.kubernetes.io/rewrite-target: /$1
    nginx.ingress.kubernetes.io/use-regex: "true"

  path: /grafana/?(.*)
  hosts:
    - #domain#

grafana.ini:
  server:
    domain: #domain#
    root_url: "%(protocol)s://%(domain)s/grafana"
    serve_from_sub_path: true
