namespace: eshop
protocol: https
tenantId: 63060cb1-0960-4615-8769-b110040fa763
keyVaultName: kube-dev-a-crypt

apiGatewayUrlExternal: webshopping-gw.dev.eshop.boringtestdomain.nl
identityUrlExternal: identity-api.dev.eshop.boringtestdomain.nl
blazorClientUrlExternal: blazor-client.dev.eshop.boringtestdomain.nl
seqFqdn: seq.dev.eshop.boringtestdomain.nl

dapr:
  keyVaultClientId: f3290e0a-123d-4d9c-9b2d-b1bd2384f634
  pubsub:
    azureEnabled: true

ingress:
  forceSSLRedirect: true
  certManager:
    enabled: true
    environment: prod
  tls:
    - secretName: webshopping-gw-tls
      hosts:
        - webshopping-gw.dev.eshop.boringtestdomain.nl
    - secretName: identity-api-tls
      hosts:
        - identity-api.dev.eshop.boringtestdomain.nl
    - secretName: blazor-client-tls
      hosts:
        - blazor-client.dev.eshop.boringtestdomain.nl

identity:
  #secretProviderVolume: {}
  secretProviderVolume: |
    volumes:
      - name: secrets-store01-inline
        csi:
          driver: secrets-store.csi.k8s.io
          readOnly: true
          volumeAttributes:
            secretProviderClass: "azure-csi-secret-provider"
  #secretProviderVolumeMount: {}
  secretProviderVolumeMount: |
    volumeMounts:
      - name: secrets-store01-inline
        mountPath: "/mnt/secrets-store"
  #sqlConnectionStringEnvironmentVariable: {}
  sqlConnectionStringEnvironmentVariable: |
    - name: ConnectionStrings__IdentityDB
      valueFrom:
        secretKeyRef:
          name: azure-sql-connection-string-secret
          key: secret

basketImageTag: latest
blazorClientImageTag: latest
catalogImageTag: latest
identityImageTag: latest
orderingImageTag: latest
paymentImageTag: latest
webshoppingaggImageTag: latest