global:
  namespace: eshop
  protocol: https
  apiGatewayUrlExternal: webshopping-gw.eshop.boringtestdomain.nl
  identityUrlExternal: identity-api.eshop.boringtestdomain.nl
  blazorClientUrlExternal: blazor-client.eshop.boringtestdomain.nl
  seqFqdn: seq.eshop.boringtestdomain.nl
  sqlConnectionString: Server=sqldata;Database=Microsoft.eShopOnDapr.Service.IdentityDb;User Id=sa;Password=Pass@word;TrustServerCertificate=true
  # Server=servername.database.windows.net;Authentication=Active Directory MSI;Database=testdb;User Id=207ff781-d583-4439-9c7b-87b8afbb3be6;

  ingress:
    forceSSLRedirect: true
    certManager:
      enabled: true
      environment: staging
    tls:
      - secretName: webshopping-gw-tls
        hosts:
          - webshopping-gw.eshop.boringtestdomain.nl
      - secretName: identity-api-tls
        hosts:
          - identity-api.eshop.boringtestdomain.nl
      - secretName: blazor-client-tls
        hosts:
          - blazor-client.eshop.boringtestdomain.nl

blazorClientImageTag: latest
catalogImageTag: latest
identityImageTag: latest
orderingImageTag: latest
paymentImageTag: latest
webshoppingaggImageTag: latest

basket-api:
  enabled: true
identity-api:
  enabled: true
payment-api:
  enabled: true
blazorclient:
  enabled: true
catalog-api:
  enabled: true
ordering-api:
  enabled: true
webshoppingagg: 
  enabled: true