kind: ConfigMap
apiVersion: v1
metadata:
  name: basket-cm
  namespace: {{ .Values.global.namespace }}
  labels:
    app: eshop
    service: basket
data:
  ASPNETCORE_ENVIRONMENT: Development
  ASPNETCORE_URLS: http://0.0.0.0:80
  IdentityUrl: http://identity-api
  IdentityUrlExternal: {{ .Values.global.protocol }}://{{ .Values.global.hostName }}/identity
  SeqServerUrl: http://seq

---

kind: Deployment
apiVersion: apps/v1
metadata:
  name: basket
  namespace: {{ .Values.global.namespace }}
  labels:
    app: eshop
    service: basket
spec:
  replicas: 1
  selector:
    matchLabels:
      service: basket
  template:
    metadata:
      labels:
        app: eshop
        service: basket
        aadpodidbinding: key-vault-identity
      annotations:
        dapr.io/enabled: "true"
        dapr.io/app-id: "basket-api"
        dapr.io/app-port: "80"
        dapr.io/config: "dapr-config"
        dapr.io/log-as-json: "true"
    spec:
      containers:
        - name: basket-api
          image: {{ .Values.global.containerRegistry}}/basket.api:{{ .Values.basketImageTag }}
          imagePullPolicy: IfNotPresent
          ports:
            - name: api-http
              containerPort: 80
              protocol: TCP
          envFrom:
            - configMapRef:
                name: basket-cm
          readinessProbe:
            httpGet:
              path: /hc
              port: 80
            initialDelaySeconds: 5
            periodSeconds: 5

---

apiVersion: v1
kind: Service
metadata:
  name: basket-api
  namespace: {{ .Values.global.namespace }}
  labels:
    app: eshop
    service: basket
spec:
  ports:
    - port: 80
      targetPort: 80
      protocol: TCP
      name: http
  selector:
    service: basket
