{{- if eq .Values.dapr.pubsub.azureEnabled true -}}
apiVersion: dapr.io/v1alpha1
kind: Component
metadata:
  name: pubsub
  namespace: {{ .Values.global.namespace }}
spec:
  type: pubsub.azure.servicebus
  version: v1
  metadata:
    - name: connectionString
      secretKeyRef:
        name: sb-connection-string
        key: sb-connection-string
auth:
  secretStore: azurekeyvault
{{- end }}