kind: Deployment
apiVersion: apps/v1
metadata:
  name: seq
  namespace: {{ .Values.global.namespace }}
  labels:
    app: eshop
    service: seq
spec:
  replicas: 1
  selector:
    matchLabels:
      service: seq
  template:
    metadata:
      labels:
        app: eshop
        service: seq
    spec:
      containers:
      - name: seq
        image: datalust/seq:latest
        imagePullPolicy: IfNotPresent
        ports:
          - name: seq-http
            containerPort: 80
            protocol: TCP
        env:
          - name: ACCEPT_EULA
            value: "Y"
          - name: SEQ_API_CANONICALURI
            value: "http://{{ .Values.global.hostName }}/log/"

---

kind: Service
apiVersion: v1
metadata:
  name: seq
  namespace: {{ .Values.global.namespace }}
  labels:
    app: eshop
    service: seq
spec:
  ports:
    - name: ui
      port: 80
      targetPort: seq-http
  selector:
    service: seq

