name: basket-api

on:
  workflow_dispatch:
  push:
    branches:
    - main

    paths:
    - src/BuildingBlocks/**
    - src/Services/Basket/**
    - .github/workflows/basket-api.yml
  
  pull_request:
    branches:
    - main

    paths:
    - src/BuildingBlocks/**
    - src/Services/Basket/**
    - .github/workflows/basket-api.yml
    
jobs:
  call-build-push-deploy-workflow:
    uses: ./.github/workflows/build-push-deploy.yml
    with:
      SERVICE: basket-api
      IMAGE_TAG_NAME: basketApiImageTag
    secrets: inherit
