name: basket-api

on:
  workflow_dispatch:
  push:
    branches:
    - main

    paths:
    - src/BuildingBlocks/**
    - src/Services/Basket/**
    - .github/workflows/basket-api.yml
  
  pull_request:
    branches:
    - main

    paths:
    - src/BuildingBlocks/**
    - src/Services/Basket/**
    - .github/workflows/basket-api.yml
    
jobs:
  app-cicd:
    uses: ./.github/workflows/app-cicd.yml
    with:
      SERVICE: basket-api
      IMAGE_TAG_NAME: basketImageTag
      BUILD_PATH: src/Services/Basket/Basket.API
      CSPROJ_FILE: Basket.API
      BUILD_DOTNET: true
    secrets: inherit
