name: blazor-client

on:
  workflow_dispatch:
  push:
    branches:
    - main

    paths:
    - src/BuildingBlocks/**
    - src/Web/**
    - .github/workflows/blazor-client.yml
  
  pull_request:
    branches:
    - main
    
    paths:
    - src/BuildingBlocks/**
    - src/Web/**
    - .github/workflows/blazor-client.yml

jobs:
  app-cicd:
    uses: ./.github/workflows/app-cicd.yml
    with:
      SERVICE: blazor-client
      IMAGE_TAG_NAME: blazorClientImageTag
      BUILD_PATH: src/Web/BlazorClient.Host
      CSPROJ_FILE: BlazorClient.Host
      BUILD_DOTNET: true
    secrets: inherit