name: catalog-api

on:
  workflow_dispatch:
  push:
    branches:
    - main

    paths:
    - src/BuildingBlocks/**
    - src/Services/Catalog/**
    - .github/workflows/catalog-api.yml
  
  pull_request:
    branches:
    - main
    
    paths:
    - src/BuildingBlocks/**
    - src/Services/Catalog/**
    - .github/workflows/catalog-api.yml

jobs:
  app-cicd:
    uses: ./.github/workflows/app-cicd.yml
    with:
      SERVICE: catalog-api
      IMAGE_TAG_NAME: catalogImageTag
      BUILD_PATH: src/Services/Catalog/Catalog.API
      CSPROJ_FILE: Catalog.API
      BUILD_DOTNET: true
    secrets: inherit