name: deploy-eshop

on:
  workflow_run:
   workflows: ["helm-ci"]
   types:
     - completed
  # workflow_dispatch:
  #   push:
  #   branches:
  #   - main

  #   paths:
  #   - .github/workflows/deploy-eshop-latest.yml

env:
  ENVIRONMENT: kube-dev-a #TODO
  ACR_NAME: demo01cr
  CHART_VERSION: 1.0.0-latest # use hardcoded latest version by initial rollout

jobs:
  deploy-to-aks:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    steps:
    - name: Azure Kubernetes set context
      uses: Azure/aks-set-context@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}
        resource-group: ${{ env.ENVIRONMENT }}-cluster-rg
        cluster-name: ${{ env.ENVIRONMENT }}-cluster

    - name: Get code from the repository
      uses: actions/checkout@v1
      with:
        ref: main

    - name: Helm tool installer
      uses: Azure/setup-helm@v1

    - name: Azure Login
      uses: Azure/login@v1.1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}

    - name: login to acr using helm
      run: |
        echo $ | helm registry login  ${{ env.ACR_NAME }}.azurecr.io --username ${{ secrets.USERNAME }} --password ${{ secrets.PASSWORD }}
    
    - name: deploy eshop
      run: |
        helm upgrade --install eshop oci://demo01cr.azurecr.io/helm/eshopondapr --version ${{ env.CHART_VERSION }} -f ./deploy/helm-values/values.${{ env.ENVIRONMENT }}.yaml

