name: helm-ci

on:
  workflow_dispatch:
  push:
    branches:
    - main

    paths:
    - deploy/charts/**
    - .github/workflows/helm-ci.yml
  
  pull_request:
    branches:
    - main

    paths:
    - deploy/charts/**
    - .github/workflows/helm-ci.yml

env:
  HELM_EXPERIMENTAL_OCI: 1
  HELM_VERSION_TO_INSTALL: latest
  ACR_NAME: demo01cr
  ACR_REPO_NAME: helm/e-shop

jobs:
  build:
    name: publish acr
    runs-on: ubuntu-latest
    environment: prod
    steps:
      - uses: actions/checkout@v2
        name: checkout repo
      
      - name: install helm
        uses: Azure/setup-helm@v1
        # with:
        #   version: ${{ env.HELM_VERSION_TO_INSTALL }}# default is latest
      
      - name: login to acr using helm
        run: |
          echo $ | helm registry login $.azurecr.io --username $ --password-stdin 
      
      - name: save helm chart to local registry
        run: |
          helm chart save $/src/azure-vote-helm-chart/ $.azurecr.io/$:latest
            
      - name: publish chart to acr
        run: |
          helm chart push $.azurecr.io/$:latest