name: helm-ci

on:
  # workflow_run:
  #   workflows: ["plumbing"]
  #   types:
  #     - completed
  workflow_dispatch:
    push:
      branches:
      - main

      paths:
      - deploy/helm-values/**

env:
  ACR_NAME: demo01cr
  CHART_VERSION: 1.0.1-latest # use hardcoded latest version by initial rollout

jobs:
  push-helm-chart:
    name: publish Helm chart eshopondapr to ACR
    # if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest
    environment: prod
    steps:
      - name: checkout repo
        uses: actions/checkout@v2
      
      - name: install Helm
        uses: Azure/setup-helm@v1
      
      - name: login to ACR using Helm
        run: |
          echo $ | helm registry login  ${{ env.ACR_NAME }}.azurecr.io --username ${{ secrets.USERNAME }} --password ${{ secrets.PASSWORD }}

      - name: lint and check the chart
        run: |
          helm lint deploy/charts/eshop
          helm template deploy/charts/eshop

      - name: save Helm chart to local registry
        run: |
          helm package deploy/charts/eshop --version ${{ env.CHART_VERSION }}
            
      - name: publish chart to ACR
        run: |
          helm push eshopondapr-${{ env.CHART_VERSION }}.tgz oci://${{ env.ACR_NAME }}.azurecr.io/helm