name: helm-ci

on:
  workflow_dispatch:
  push:
    branches:
    - main

    paths:
    - deploy/charts/**
    - .github/workflows/helm-ci.yml
  
  pull_request:
    branches:
    - main

    paths:
    - deploy/charts/**
    - .github/workflows/helm-ci.yml

env:
  HELM_EXPERIMENTAL_OCI: 1
  HELM_VERSION_TO_INSTALL: 3.8.0
  ACR_NAME: demo01cr
  ACR_REPO_NAME: helm/e-shop
  CHART_VERSION: 1.1 # check if we will use commit sha

jobs:
  build:
    name: publish acr
    runs-on: ubuntu-latest
    environment: prod
    steps:
      - uses: actions/checkout@v2
        name: checkout repo
      
      - name: install helm
        uses: Azure/setup-helm@v1
        # with:
        #   version: ${{ env.HELM_VERSION_TO_INSTALL }}# default is latest
      
      - name: login to acr using helm
        run: |
          echo $ | helm registry login  ${{ env.ACR_NAME }}.azurecr.io --username ${{ secrets.USERNAME }} --password ${{ secrets.PASSWORD }}
      
      - name: save helm chart to local registry
        run: |
          helm package deploy/charts/eshop --version ${{ env.CHART_VERSION }}
            
      - name: publish chart to acr
        run: |
          helm push eShopOnDapr-${{ env.CHART_VERSION }}.tgz oci://${{ env.ACR_NAME }}.azurecr.io/eShopOnDapr-${{ env.CHART_VERSION }}