name: identity-api

on:
  workflow_dispatch:
  push:
    branches:
    - main

    paths:
    - src/BuildingBlocks/**
    - src/Services/Identity/**
    - .github/workflows/identity-api.yml
  
  pull_request:
    branches:
    - main

    paths:
    - src/BuildingBlocks/**
    - src/Services/Identity/**
    - .github/workflows/identity-api.yml

jobs:
  app-cicd:
    uses: ./.github/workflows/app-cicd.yml
    with:
      SERVICE: identity-api
      IMAGE_TAG_NAME: identityImageTag
      BUILD_DOTNET: false
    secrets: inherit