name: ordering-api

on:
  workflow_dispatch:
  push:
    branches:
    - main

    paths:
    - src/BuildingBlocks/**
    - src/Services/Ordering/**
    - .github/workflows/ordering-api.yml
  
  pull_request:
    branches:
    - main

    paths:
    - src/BuildingBlocks/**
    - src/Services/Ordering/**
    - .github/workflows/ordering-api.yml

jobs:
  app-cicd:
    uses: ./.github/workflows/app-cicd.yml
    with:
      SERVICE: ordering-api
      IMAGE_TAG_NAME: orderingImageTag
      BUILD_PATH: src/Services/Ordering/Ordering.API
      CSPROJ_FILE: Ordering.API
      BUILD_DOTNET: true
    secrets: inherit