name: payment-api

on:
  workflow_dispatch:
  push:
    branches:
    - main

    paths:
    - src/BuildingBlocks/**
    - src/Services/Payment/**
    - .github/workflows/payment-api.yml
  
  pull_request:
    branches:
    - main

    paths:
    - src/BuildingBlocks/**
    - src/Services/Payment/**
    - .github/workflows/payment-api.yml

jobs:
  app-cicd:
    uses: ./.github/workflows/app-cicd.yml
    with:
      SERVICE: payment-api
      IMAGE_TAG_NAME: paymentImageTag
      BUILD_DOTNET: false
    secrets: inherit