name: kube-demo

on:
  workflow_dispatch:

jobs:
  terraform-kube-deplpy:
    uses: ./.github/workflows/terraform-kube-deploy.yml
    with:
      PREFIX: kube-demo
      TF_COMMAND: apply
    secrets: inherit