name: kube-sandbox

on:
  workflow_dispatch:

jobs:
  terraform-kube-deploy:
    uses: ./.github/workflows/terraform-kube-deploy.yml
    with:
      PREFIX: kube-sandbox
      TF_COMMAND: apply
    secrets: inherit