name: kube-deploy

on:
  workflow_call:
    inputs:
      PREFIX:
        required: true
        type: string
      TF_COMMAND:
        required: true
        type: string
    secrets:
      ARM_CLIENT_ID:
        required: true
      ARM_CLIENT_SECRET:
        required: true
      ARM_SUBSCRIPTION_ID:
        required: true
      ARM_TENANT_ID:
        required: true
      TF_VAR_tenant_id:
        required: true
      TF_VAR_vm_admin_password:
        required: true
      TF_VAR_backend_storage_account_name:
        required: true
      TF_VAR_backend_resource_group_name:
        required: true

permissions:
  id-token: write
  contents: read

jobs:
  terraform:
    runs-on: ubuntu-latest
    env:
      ARM_ACCESS_KEY: ${{ secrets.ARM_ACCESS_KEY }}
      ARM_CLIENT_ID: ${{ secrets.ARM_CLIENT_ID }}
      ARM_CLIENT_SECRET: ${{ secrets.ARM_CLIENT_SECRET }}
      ARM_SUBSCRIPTION_ID: ${{ secrets.ARM_SUBSCRIPTION_ID }}
      ARM_TENANT_ID: ${{ secrets.ARM_TENANT_ID }}
      TF_VAR_tenant_id: ${{ secrets.ARM_TENANT_ID }}
      TF_VAR_vm_admin_password: ${{ secrets.VM_ADMIN_PASSWORD }}
      TF_VAR_backend_storage_account_name: ${{ secrets.TF_VAR_BACKEND_STORAGE_ACCOUNT_NAME }}
      TF_VAR_backend_resource_group_name: ${{ secrets.TF_VAR_BACKEND_STORAGE_ACCOUNT_NAME }}
      TF_WORK_DIR: "deploy/terraform/environments/${{ inputs.PREFIX }}"
      TF_STATE_KEY: ${{ inputs.PREFIX }}

    steps:
      - uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Checkout
        uses: actions/checkout@v2

      - name: Terraform Init
        run: |
          terraform -chdir=$TF_WORK_DIR init \
            -backend-config "resource_group_name=$TF_VAR_backend_resource_group_name" \
            -backend-config "storage_account_name=$TF_VAR_backend_resource_group_name" \
            -backend-config "key=$TF_STATE_KEY" -upgrade

      - name: Terraform Plan
        run: |
          terraform -chdir="$TF_WORK_DIR" plan

        # if: github.ref == 'refs/heads/main' && github.event_name == 'push'
      - name: Terraform Apply
        if: ${{ inputs.TF_COMMAND }} == 'apply'
        run: |
          terraform -chdir=$TF_WORK_DIR apply -auto-approve

      - name: Terraform Destroy
        if: ${{ inputs.TF_COMMAND }} == 'destroy'
        run: |
          terraform -chdir=$TF_WORK_DIR init \
          -backend-config "resource_group_name=$TF_VAR_backend_resource_group_name" \
          -backend-config "storage_account_name=$TF_VAR_backend_resource_group_name" \
          -backend-config "key=$TF_STATE_KEY" -upgrade
          terraform -chdir=$TF_WORK_DIR apply -destroy -auto-approve