name: webshoppingagg

on:
  workflow_dispatch:
  push:
    branches:
    - main

    paths:
    - src/ApiGateways/Aggregators/Web.Shopping.HttpAggregator/**
    - .github/workflows/webshoppingagg.yml
  
  pull_request:
    branches:
    - main

    paths:
    - src/ApiGateways/Aggregators/Web.Shopping.HttpAggregator/**
    - .github/workflows/webshoppingagg.yml

jobs:
  app-cicd:
    uses: ./.github/workflows/app-cicd.yml
    with:
      SERVICE: webshoppingagg
      IMAGE_TAG_NAME: webshoppingaggImageTag
      BUILD_DOTNET: false
    secrets: inherit