name: webshoppingapigw

on:
  workflow_dispatch:
  push:
    branches:
    - main

    paths:
    - src/ApiGateways/Envoy/**
    - .github/workflows/webshoppingapigw.yml
  
  pull_request:
    branches:
    - main

    paths:
    - src/ApiGateways/Envoy/**
    - .github/workflows/webshoppingapigw.yml

jobs:
  app-cicd:
    uses: ./.github/workflows/app-cicd.yml
    with:
      SERVICE: webshoppingapigw
      IMAGE_TAG_NAME: webshoppingapigwImageTag
      BUILD_DOTNET: false
    secrets: inherit